version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter-test
    versions:
    - 7.15.0
  - dependency-name: org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter-rest
    versions:
    - 7.15.0
  - dependency-name: org.camunda.bpm.springboot:camunda-bpm-spring-boot-starter-webapp
    versions:
    - 7.15.0
  - dependency-name: org.camunda.bpm:camunda-bom
    versions:
    - 7.15.0
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.palantir.docker
    versions:
    - 0.26.0
  - dependency-name: io.spring.dependency-management
    versions:
    - 1.0.11.RELEASE
